runtime: python310
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "gs://healthcare-system2024.appspot.com/healthcare-system2024-81a9407f7f7d.json"  # Path to the Cloud Storage file

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto
